#!/bin/sh
#
# Ignore specific files when committing
# https://git-scm.com/docs/githooks#_pre_commit

files="pre-commits/ignore
"

printf '%s' "$files" |
    while IFS='' read -r file; do
        git reset "$file" >/dev/null
    done

changes=$(git diff --cached --name-only | wc -l)
if [ "$changes" -eq 0 ]; then
    echo "Nothing to commit, exiting..."
    exit 1
fi
